### PR TITLE
Update libmpegts.c

### PR DESCRIPTION
**Pull request by leesei**
Fix access violation on `pcr_list` (found using valgrind)

### CODE REVIEW

**Comment by kierank** [comment]
Hi,

What line does the access violation occur on?

Kieran

**Comment by leesei** [comment]
Ln 2053

**Comment by kierank** [comment]
Unless I'm being stupid, isn't the code ok as it is?

**Comment by leesei** [comment]
if `w->num_pcrs` = 500 and `w->pcr_list_alloced` = 500
ln 2053 is trying to fill `w->pcr_list[500]` with `pcr`, note only [0-499] are accessible in `w->pcr_list`

**Pull request merged**
